# .pre-commit-config.yaml
repos:
  # isort configuration
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1  # Specify the version (you can change to latest stable)
    hooks:
      - id: isort
        name: isort
        args:
          - "--profile"
          - "black"
        exclude: "^(tests|docs)/.*"  # Exclude test and docs directories
        files: ^autodeep/.*\.py$ # Only check Python files


  # flake8 configuration
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2  # Specify version (can be updated)
    hooks:
      - id: flake8
        name: flake8
        args:
          - "--max-line-length=150"  # Max line length for flake8 (PEP 8 compatible)
          - "--exclude=.tox,.git,.venv,build,dist"  # Commonly excluded folders
        exclude: "^(tests|docs)/.*"  # Exclude test and docs directories
        files: ^autodeep/.*\.py$  # Only check Python files

  # pylint configuration
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.5  # Specify version, update if needed
    hooks:
      - id: pylint
        name: pylint
        args:
          - "--max-line-length=150"  # Max line length for pylint (PEP 8 compatible)
          - "--disable=missing-docstring,invalid-name"  # Disable warnings for missing docstrings and invalid names (you can customize this)
        exclude: "^(tests|docs)/.*"  # Exclude test and docs directories
        files: ^autodeep/.*\.py$  # Only check Python files

  # black configuration
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Specify version, can update to latest stable version
    hooks:
      - id: black
        name: black
        args:
          - "--line-length=150"
          - "--skip-string-normalization"  # Avoid normalizing string quotes
        exclude: "^(tests|docs)/.*"  # Exclude test and docs directories
        files: ^autodeep/.*\.py$  # Only check Python files
