random_state: 4200
retrain: True

include_models:
  - XGB  # Extreme Gradient Boosting
  - CatBoost
  - MLP  # Multi-Layer Perceptron
  - TabNet  # TabNet Classifier
  - GATE
  - resnet
  - S1DCNN
  - CategoryEmbedding
  - FTTransformer
  - TabTransformer
  - GANDALF
  - AutoInt
  - Node

model_configs:

  catboost:
    data_params:
      normalize_features: mean_std
      encode_categorical: False  # for dataloader
      return_extra_info: True  # for dataloader

    default_params:
      retrain: False
      validation_fraction: 0.15
      early_stopping_rounds: 100
      verbose: false
      iterations: 500

    param_grid:
      early_stopping_rounds: 
        - 100
        - 50
      iterations:
        - 100 
        - 500

  categoryembedding:

    data_params:
      normalize_features: mean_std
      encode_categorical: False  # for dataloader
      return_extra_info: True  # for dataloader
    

    default_params:
      early_stopping_rounds: 10
      verbose: false
      iterations: 20
      retrain: False
      auto_lr_find: False
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 20

    param_grid:
      batch_size:
        - 128
        - 1024
      layers:
        - "128-64-32"
        - "256-128"
        - "256-128-64-32"
        - "32-16"
        - "64-32-16"
        - "64-32"
      activation:
        - "ReLU"
        - "LeakyReLU"

      optimizer_fn:
        Adam:
          weight_decay:
            - 0.0
            - 0.0000001
          learning_rate:
            - 0.001
            - 0.0001
        SGD:
          weight_decay:
            - 0.0
            - 0.0000001
          momentum:
            - 0.0
            - 0.9
          learning_rate:
            - 0.001
            - 0.00001
        AdamW:
          weight_decay:
            - 0.0
            - 0.0000001
          learning_rate:
            - 0.001
            - 0.0001
      scheduler_fn:
        ReduceLROnPlateau:
          factor:
            - 0.1
            - 0.01
          patience:
            - 5
            - 10
        StepLR:
          step_size:
            - 10
            - 30
          gamma:
            - 0.1
            - 0.5
        ExponentialLR:
          gamma:
            - 0.9
            - 0.99

  xgb:

    data_params:
      normalize_features: false
      encode_categorical: True
      return_extra_info: False

    default_params:
      retrain: True
      early_stopping_rounds: 30
      verbose: false
      learning_rate: 0.3
      max_depth: 6
      n_estimators: 100
      min_child_weight: 1
      subsample: 0.8
      colsample_bytree: 0.8
      gamma: 0.0

    param_grid:
      early_stopping_rounds:
        - 30
        - 50
      learning_rate:
        - 0.3
        - 0.01
      max_depth:
        - 4
        - 6
        - 8
      n_estimators:
        - 50
        - 100
        - 200
      min_child_weight:
        - 1
        - 5
        - 10
      subsample:
        - 0.6
        - 0.8
        - 1.0
      colsample_bytree:
        - 0.6
        - 0.8
        - 1.0
      gamma:
        - 0.0
        - 0.1
        - 0.2
      
  mlp:
    data_params:
      normalize_features: mean_std
      encode_categorical: True
      return_extra_info: False

    default_params:
      early_stopping: True
      n_iter_no_change: 10
      max_iter: 1000
      hidden_layer_sizes: [32]
      activation: relu
      solver: adam
      batch_size: 1024

    param_grid:
      n_iter_no_change:
        - 10
        - 15
      max_iter:
        - 1000
        - 2000
      hidden_layer_sizes:
        - [64,32]
        - [128,64,32]
      activation:
        - relu
        - tanh
      solver:
        - adam
        - sgd
      batch_size:
        - 1024
        - 2048
