- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id014
      hyperopt_evals: 10
      validation_fraction: 0.15
      early_stopping_rounds: 30
      verbose: false
    n_estimators: &id015
    - 100
    - 5000
    max_bin: &id016
    - 256
    - 32
    tree_method: &id017
    - auto
    - hist
    max_depth: &id018
    - 4
    - 10
    learning_rate: &id019
    - 0.1
    - 0.33
    subsample: &id020
    - 0.7
    - 1.0
    colsample_bytree: &id021
    - 0.5
    - 1.0
    min_child_weight: &id022
    - 1
    - 10
    alpha: &id023
    - 0.0
    - 5.0
    gamma: &id024
    - 0.0
    - 5.0
    lambda: &id025
    - 0.0
    - 5.0
- dataset: housing
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id026
      cv_iterations: 10
      early_stopping: true
      cv_size: 5
      validation_fraction: 0.15
      n_iter_no_change: 6
      max_iter: 1000
    hidden_layer_sizes: &id027
    - - 16
      - 32
    - - 16
      - 8
    - - 32
      - 16
    - - 128
      - 64
      - 32
    activation: &id028
    - relu
    - tanh
    - logistic
    solver: &id029
    - adam
    - lbfgs
    alpha: &id030
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id031
    - 0.001
    - 0.01
    - 0.1
    beta_1: &id032
    - 0.9
    - 0.99
    - 0.8
    beta_2: &id033
    - 0.999
    - 0.9
    batch_size: &id034
    - 512
    - 1024
    - 2048
    - 4096
- dataset: housing
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id035
      hyperopt_evals: 100
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    virtual_batch_size_ratio: &id036
    - 0.125
    - 0.25
    - 0.5
    - 1.0
    batch_size: &id037
    - 512
    - 1024
    - 2048
    weights: &id038
    - 0
    - 1
    mask_type: &id039
    - sparsemax
    - entmax
    n_d: &id040
    - 6
    - 32
    n_steps: &id041
    - 1
    - 6
    gamma: &id042
    - 1.0
    - 2.0
    n_independent: &id043
    - 1
    - 3
    n_shared: &id044
    - 1
    - 3
    optimizer_fn: &id045
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id046
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: housing
  model: gate
  best_params: {}
  param_grid:
    outer_params: &id047
      hyperopt_evals: 100
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id048
    - 512
    - 1024
    - 2048
    tree_depth: &id049
    - 4
    - 7
    num_trees: &id050
    - 4
    - 16
    chain_trees: &id051
    - false
    - true
    gflu_stages: &id052
    - 3
    - 8
    gflu_dropout: &id053
    - 0.0
    - 0.01
    tree_dropout: &id054
    - 0.0
    - 0.01
    tree_wise_attention_dropout: &id055
    - 0.0
    - 0.01
    embedding_dropout: &id056
    - 0
    - 0.2
    optimizer_fn: &id057
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id058
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: housing
  model: node
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 100
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id002
    - 512
    - 1024
    - 2048
    num_layers: &id003
    - 1
    - 2
    - 3
    num_trees: &id004
    - 12
    - 128
    additional_tree_output_dim: &id005
    - 2
    - 3
    - 4
    depth: &id006
    - 5
    - 7
    choice_function: &id007
    - entmax15
    - sparsemax
    bin_function: &id008
    - entmoid15
    - sparsemoid
    input_dropout: &id009
    - 0.0
    - 0.1
    embedding_dropout: &id010
    - 0.0
    - 0.1
    embed_categorical: &id011
    - true
    - false
    optimizer_fn: &id012
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id013
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: adult
  model: node
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    num_layers: *id003
    num_trees: *id004
    additional_tree_output_dim: *id005
    depth: *id006
    choice_function: *id007
    bin_function: *id008
    input_dropout: *id009
    embedding_dropout: *id010
    embed_categorical: *id011
    optimizer_fn: *id012
    scheduler_fn: *id013
- dataset: heloc
  model: node
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    num_layers: *id003
    num_trees: *id004
    additional_tree_output_dim: *id005
    depth: *id006
    choice_function: *id007
    bin_function: *id008
    input_dropout: *id009
    embedding_dropout: *id010
    embed_categorical: *id011
    optimizer_fn: *id012
    scheduler_fn: *id013
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id014
    n_estimators: *id015
    max_bin: *id016
    tree_method: *id017
    max_depth: *id018
    learning_rate: *id019
    subsample: *id020
    colsample_bytree: *id021
    min_child_weight: *id022
    alpha: *id023
    gamma: *id024
    lambda: *id025
- dataset: covertype
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id026
    hidden_layer_sizes: *id027
    activation: *id028
    solver: *id029
    alpha: *id030
    learning_rate_init: *id031
    beta_1: *id032
    beta_2: *id033
    batch_size: *id034
- dataset: covertype
  model: resnet18
  best_params: {}
  param_grid:
    outer_params: &id059
      hyperopt_evals: 10
      num_epochs: 1000
      early_stopping: true
      early_stopping_patience: 6
      validation_fraction: 0.15
    learning_rate: &id060
    - 0.0001
    - 0.001
    batch_size: &id061
    - 512
    - 1024
    - 2048
    - 4096
    scheduler_factor: &id062
    - 0.1
    - 0.9
    scheduler_patience: &id063
    - 3
    - 5
- dataset: covertype
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: &id064
      hyperopt_evals: 10
      num_epochs: 1000
      early_stopping: true
      shuffle: true
      validation_fraction: 0.15
      early_stopping_patience: 6
    batch_size: &id065
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id066
    - 0.01
    - 0.0001
    hidden_size: &id067
    - 1024
    - 2048
    - 4096
    scheduler_factor: &id068
    - 0.1
    - 0.9
    scheduler_patience: &id069
    - 4
    - 7
- dataset: covertype
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id035
    virtual_batch_size_ratio: *id036
    batch_size: *id037
    weights: *id038
    mask_type: *id039
    n_d: *id040
    n_steps: *id041
    gamma: *id042
    n_independent: *id043
    n_shared: *id044
    optimizer_fn: *id045
    scheduler_fn: *id046
- dataset: covertype
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id047
    batch_size: *id048
    tree_depth: *id049
    num_trees: *id050
    chain_trees: *id051
    gflu_stages: *id052
    gflu_dropout: *id053
    tree_dropout: *id054
    tree_wise_attention_dropout: *id055
    embedding_dropout: *id056
    optimizer_fn: *id057
    scheduler_fn: *id058
- dataset: covertype
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: &id070
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id071
    - 0.001
    - 0.0001
    batch_size: &id072
    - 512
    - 1024
    - 2048
    embedding_initialization: &id073
    - kaiming_uniform
    - kaiming_normal
    shared_embedding_fraction: &id074
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks: &id075
    - 4
    - 10
    attn_dropout: &id076
    - 0.05
    - 0.3
    add_norm_dropout: &id077
    - 0.05
    - 0.3
    ff_dropout: &id078
    - 0.05
    - 0.3
    ff_hidden_multiplier: &id079
    - 2
    - 6
    transformer_activation: &id080
    - GEGLU
    - ReGLU
    - SwiGLU
    embedding_dropout: &id081
    - 0.05
    - 0.3
    optimizer_fn: &id082
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id083
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: &id084
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
      precision: 16
    batch_size: &id085
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id086
    - 0.001
    - 0.0001
    layers: &id087
    - 128-64-32
    - 64-32-16
    - 512-128-32
    activation: &id088
    - ReLU
    - LeakyReLU
    initialization: &id089
    - kaiming
    - xavier
    dropout: &id090
    - 0.0
    - 0.3
    optimizer_fn: &id091
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id092
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: &id093
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id094
    - 0.001
    - 0.0001
    batch_size: &id095
    - 512
    - 1024
    - 2048
    - 4096
    gflu_stages: &id096
    - 2
    - 8
    gflu_dropout: &id097
    - 0.0
    - 0.3
    embedding_dropout: &id098
    - 0.0
    - 0.3
    optimizer_fn: &id099
      Adam:
        weight_decay:
        - 0.0
        - 0.01
      AdamW:
        weight_decay:
        - 0.0
        - 0.01
    scheduler_fn: &id100
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 10
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: node
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    num_layers: *id003
    num_trees: *id004
    additional_tree_output_dim: *id005
    depth: *id006
    choice_function: *id007
    bin_function: *id008
    input_dropout: *id009
    embedding_dropout: *id010
    embed_categorical: *id011
    optimizer_fn: *id012
    scheduler_fn: *id013
- dataset: covertype
  model: autoint
  best_params: {}
  param_grid:
    outer_params: &id101
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id102
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id103
    - 0.001
    - 0.0001
    num_attn_blocks: &id104
    - 3
    - 2
    - 4
    attn_dropouts: &id105
    - 0.0
    - 0.1
    - 0.3
    has_residuals: &id106
    - true
    - false
    embedding_initialization: &id107
    - kaiming_uniform
    - kaiming_normal
    embedding_bias: &id108
    - true
    - false
    share_embedding: &id109
    - true
    - false
    share_embedding_strategy: &id110
    - add
    - fraction
    shared_embedding_fraction: &id111
    - 0.25
    - 0.1
    - 0.5
    deep_layers: &id112
    - true
    - false
    layers: &id113
    - 128-64-32
    - 64-32
    - 256-128-64
    activation: &id114
    - ReLU
    - LeakyReLU
    - Tanh
    initialization: &id115
    - kaiming
    - xavier
    - random
    dropout: &id116
    - 0.0
    - 0.2
    - 0.0
    attention_pooling: &id117
    - true
    - false
    optimizer_fn: &id118
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id119
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: tabtransformer
  best_params: {}
  param_grid:
    outer_params: &id120
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id121
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id122
    - 0.01
    - 0.0001
    embedding_bias: &id123
    - true
    - false
    embedding_initialization: &id124
    - kaiming_uniform
    - kaiming_normal
    shared_embedding_fraction: &id125
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks: &id126
    - 4
    - 10
    attn_dropout: &id127
    - 0.05
    - 0.3
    add_norm_dropout: &id128
    - 0.05
    - 0.3
    ff_dropout: &id129
    - 0.05
    - 0.3
    ff_hidden_multiplier: &id130
    - 2
    - 6
    transformer_activation: &id131
    - GEGLU
    - ReGLU
    - SwiGLU
    embedding_dropout: &id132
    - 0.05
    - 0.3
    optimizer_fn: &id133
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id134
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: catboost
  best_params: {}
  param_grid:
    outer_params: &id135
      hyperopt_evals: 10
      validation_fraction: 0.15
      early_stopping_rounds: 100
      verbose: false
    iterations: &id136
    - 200
    - 2000
    learning_rate: &id137
    - 0.001
    - 0.1
    depth: &id138
    - 4
    - 10
    l2_leaf_reg: &id139
    - 0.5
    - 5.0
    min_child_samples: &id140
    - 1
    - 100
    bagging_temperature: &id141
    - 0.1
    - 2.0
- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id014
    n_estimators: *id015
    max_bin: *id016
    tree_method: *id017
    max_depth: *id018
    learning_rate: *id019
    subsample: *id020
    colsample_bytree: *id021
    min_child_weight: *id022
    alpha: *id023
    gamma: *id024
    lambda: *id025
- dataset: creditcard
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id026
    hidden_layer_sizes: *id027
    activation: *id028
    solver: *id029
    alpha: *id030
    learning_rate_init: *id031
    beta_1: *id032
    beta_2: *id033
    batch_size: *id034
- dataset: creditcard
  model: resnet18
  best_params: {}
  param_grid:
    outer_params: *id059
    learning_rate: *id060
    batch_size: *id061
    scheduler_factor: *id062
    scheduler_patience: *id063
- dataset: creditcard
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id064
    batch_size: *id065
    learning_rate: *id066
    hidden_size: *id067
    scheduler_factor: *id068
    scheduler_patience: *id069
- dataset: creditcard
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id035
    virtual_batch_size_ratio: *id036
    batch_size: *id037
    weights: *id038
    mask_type: *id039
    n_d: *id040
    n_steps: *id041
    gamma: *id042
    n_independent: *id043
    n_shared: *id044
    optimizer_fn: *id045
    scheduler_fn: *id046
- dataset: creditcard
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id047
    batch_size: *id048
    tree_depth: *id049
    num_trees: *id050
    chain_trees: *id051
    gflu_stages: *id052
    gflu_dropout: *id053
    tree_dropout: *id054
    tree_wise_attention_dropout: *id055
    embedding_dropout: *id056
    optimizer_fn: *id057
    scheduler_fn: *id058
- dataset: creditcard
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id070
    learning_rate: *id071
    batch_size: *id072
    embedding_initialization: *id073
    shared_embedding_fraction: *id074
    num_attn_blocks: *id075
    attn_dropout: *id076
    add_norm_dropout: *id077
    ff_dropout: *id078
    ff_hidden_multiplier: *id079
    transformer_activation: *id080
    embedding_dropout: *id081
    optimizer_fn: *id082
    scheduler_fn: *id083
- dataset: creditcard
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: *id084
    batch_size: *id085
    learning_rate: *id086
    layers: *id087
    activation: *id088
    initialization: *id089
    dropout: *id090
    optimizer_fn: *id091
    scheduler_fn: *id092
- dataset: creditcard
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: *id093
    learning_rate: *id094
    batch_size: *id095
    gflu_stages: *id096
    gflu_dropout: *id097
    embedding_dropout: *id098
    optimizer_fn: *id099
    scheduler_fn: *id100
- dataset: creditcard
  model: node
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    num_layers: *id003
    num_trees: *id004
    additional_tree_output_dim: *id005
    depth: *id006
    choice_function: *id007
    bin_function: *id008
    input_dropout: *id009
    embedding_dropout: *id010
    embed_categorical: *id011
    optimizer_fn: *id012
    scheduler_fn: *id013
- dataset: creditcard
  model: autoint
  best_params: {}
  param_grid:
    outer_params: *id101
    batch_size: *id102
    learning_rate: *id103
    num_attn_blocks: *id104
    attn_dropouts: *id105
    has_residuals: *id106
    embedding_initialization: *id107
    embedding_bias: *id108
    share_embedding: *id109
    share_embedding_strategy: *id110
    shared_embedding_fraction: *id111
    deep_layers: *id112
    layers: *id113
    activation: *id114
    initialization: *id115
    dropout: *id116
    attention_pooling: *id117
    optimizer_fn: *id118
    scheduler_fn: *id119
- dataset: creditcard
  model: tabtransformer
  best_params: {}
  param_grid:
    outer_params: *id120
    batch_size: *id121
    learning_rate: *id122
    embedding_bias: *id123
    embedding_initialization: *id124
    shared_embedding_fraction: *id125
    num_attn_blocks: *id126
    attn_dropout: *id127
    add_norm_dropout: *id128
    ff_dropout: *id129
    ff_hidden_multiplier: *id130
    transformer_activation: *id131
    embedding_dropout: *id132
    optimizer_fn: *id133
    scheduler_fn: *id134
- dataset: creditcard
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id135
    iterations: *id136
    learning_rate: *id137
    depth: *id138
    l2_leaf_reg: *id139
    min_child_samples: *id140
    bagging_temperature: *id141
