- dataset: iris
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id001
      cv_iterations: 10
      early_stopping: true
      cv_size: 5
      validation_fraction: 0.15
      hyperopt_evals: 50
      n_iter_no_change: 50
      max_iter: 1000
    hidden_layer_sizes: &id002
    - - 64
      - 32
      - 16
    - - 256
      - 128
      - 64
      - 32
    - - 128
      - 64
      - 32
      - 16
    activation: &id003
    - relu
    - tanh
    - logistic
    solver: &id004
    - adam
    - lbfgs
    alpha: &id005
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id006
    - 0.0001
    - 0.01
    - 0.1
    beta_1: &id007
    - 0.99
    - 0.8
    beta_2: &id008
    - 0.999
    - 0.9
    batch_size: &id009
    - 32
    - 64
    - 128
    - 256
- dataset: titanic
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
- dataset: breastcancer
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
- dataset: ageconditions
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
- dataset: iris
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id010
      hyperopt_evals: 50
      auto_lr_find: true
      precision: 16
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    virtual_batch_size_ratio: &id011
    - 0.125
    - 0.25
    - 0.5
    - 1.0
    batch_size: &id012
    - 32
    - 64
    - 128
    - 256
    weights: &id013
    - 0
    - 1
    mask_type: &id014
    - sparsemax
    - entmax
    n_d: &id015
    - 6
    - 32
    n_steps: &id016
    - 1
    - 6
    gamma: &id017
    - 1.0
    - 2.0
    n_independent: &id018
    - 1
    - 3
    n_shared: &id019
    - 1
    - 3
    optimizer_fn: &id020
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id021
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: titanic
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id010
    virtual_batch_size_ratio: *id011
    batch_size: *id012
    weights: *id013
    mask_type: *id014
    n_d: *id015
    n_steps: *id016
    gamma: *id017
    n_independent: *id018
    n_shared: *id019
    optimizer_fn: *id020
    scheduler_fn: *id021
- dataset: breastcancer
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id010
    virtual_batch_size_ratio: *id011
    batch_size: *id012
    weights: *id013
    mask_type: *id014
    n_d: *id015
    n_steps: *id016
    gamma: *id017
    n_independent: *id018
    n_shared: *id019
    optimizer_fn: *id020
    scheduler_fn: *id021
- dataset: ageconditions
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id010
    virtual_batch_size_ratio: *id011
    batch_size: *id012
    weights: *id013
    mask_type: *id014
    n_d: *id015
    n_steps: *id016
    gamma: *id017
    n_independent: *id018
    n_shared: *id019
    optimizer_fn: *id020
    scheduler_fn: *id021
- dataset: iris
  model: resnet
  best_params: {}
  param_grid:
    outer_params: &id022
      hyperopt_evals: 50
      max_epochs: 1000
      early_stopping: true
      early_stopping_patience: 10
      validation_fraction: 0.15
    batch_size: &id023
    - 32
    - 64
    - 128
    - 256
    resnet_depth: &id024
    - resnet18
    - resnet34
    - resnet50
    optimizer_fn: &id025
      Adam:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.001
      AdamW:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.001
    scheduler_fn: &id026
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: titanic
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id022
    batch_size: *id023
    resnet_depth: *id024
    optimizer_fn: *id025
    scheduler_fn: *id026
- dataset: breastcancer
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id022
    batch_size: *id023
    resnet_depth: *id024
    optimizer_fn: *id025
    scheduler_fn: *id026
- dataset: ageconditions
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id022
    batch_size: *id023
    resnet_depth: *id024
    optimizer_fn: *id025
    scheduler_fn: *id026
