- dataset: diabetes
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 50
      auto_lr_find: true
      precision: 16
      tol: 0.001
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 3
    virtual_batch_size_ratio: &id002
    - 0.125
    - 0.25
    - 0.5
    - 1.0
    batch_size: &id003
    - 1024
    - 2048
    - 4096
    weights: &id004
    - 0
    - 1
    mask_type: &id005
    - sparsemax
    - entmax
    n_d: &id006
    - 6
    - 24
    n_steps: &id007
    - 3
    - 7
    gamma: &id008
    - 1.0
    - 2.0
    n_independent: &id009
    - 2
    - 3
    n_shared: &id010
    - 2
    - 3
    optimizer_fn: &id011
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id012
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: breastcancer
  model: resnet
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 50
      max_epochs: 1000
      early_stopping: true
      early_stopping_patience: 10
      tol: 0.0001
      validation_fraction: 0.15
    batch_size:
    - 32
    - 64
    - 128
    - 256
    resnet_depth:
    - resnet18
    - resnet34
    - resnet50
    optimizer_fn:
      Adam:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.001
      AdamW:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: creditcard
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id001
    virtual_batch_size_ratio: *id002
    batch_size: *id003
    weights: *id004
    mask_type: *id005
    n_d: *id006
    n_steps: *id007
    gamma: *id008
    n_independent: *id009
    n_shared: *id010
    optimizer_fn: *id011
    scheduler_fn: *id012
- dataset: covertype
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id001
    virtual_batch_size_ratio: *id002
    batch_size: *id003
    weights: *id004
    mask_type: *id005
    n_d: *id006
    n_steps: *id007
    gamma: *id008
    n_independent: *id009
    n_shared: *id010
    optimizer_fn: *id011
    scheduler_fn: *id012
- dataset: diabetes
  model: gate
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 50
      auto_lr_find: true
      precision: 16
      tol: 0.001
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 3
    batch_size:
    - 1024
    - 2048
    - 4096
    tree_depth:
    - 4
    - 6
    num_trees:
    - 4
    - 8
    gflu_stages:
    - 3
    - 8
    gflu_dropout:
    - 0.0
    - 0.05
    tree_dropout:
    - 0.0
    - 0.05
    tree_wise_attention_dropout:
    - 0.0
    - 0.05
    embedding_dropout:
    - 0
    - 0.2
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
