- dataset: diabetes
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id001
      cv_iterations: 10
      early_stopping: true
      cv_size: 5
      validation_fraction: 0.15
      hyperopt_evals: 50
      n_iter_no_change: 30
      max_iter: 1000
    hidden_layer_sizes: &id002
    - - 64
      - 32
      - 16
    - - 256
      - 128
      - 64
      - 32
    - - 128
      - 64
      - 32
      - 16
    activation: &id003
    - relu
    - tanh
    - logistic
    solver: &id004
    - adam
    - lbfgs
    alpha: &id005
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id006
    - 0.0001
    - 0.01
    - 0.1
    beta_1: &id007
    - 0.99
    - 0.8
    beta_2: &id008
    - 0.999
    - 0.9
    batch_size: &id009
    - 512
    - 1024
    - 2048
- dataset: housing
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
- dataset: creditcard
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
- dataset: covertype
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id001
    hidden_layer_sizes: *id002
    activation: *id003
    solver: *id004
    alpha: *id005
    learning_rate_init: *id006
    beta_1: *id007
    beta_2: *id008
    batch_size: *id009
