- dataset: creditcard
  model: node
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 50
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 8
    batch_size: &id002
    - 512
    - 1024
    num_layers: &id003
    - 1
    - 2
    - 3
    num_trees: &id004
    - 12
    - 128
    additional_tree_output_dim: &id005
    - 2
    - 3
    - 4
    depth: &id006
    - 5
    - 7
    choice_function: &id007
    - entmax15
    - sparsemax
    bin_function: &id008
    - entmoid15
    - sparsemoid
    input_dropout: &id009
    - 0.0
    - 0.1
    embedding_dropout: &id010
    - 0.0
    - 0.1
    embed_categorical: &id011
    - true
    - false
    optimizer_fn: &id012
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id013
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: node
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    num_layers: *id003
    num_trees: *id004
    additional_tree_output_dim: *id005
    depth: *id006
    choice_function: *id007
    bin_function: *id008
    input_dropout: *id009
    embedding_dropout: *id010
    embed_categorical: *id011
    optimizer_fn: *id012
    scheduler_fn: *id013
- dataset: creditcard
  model: autoint
  best_params: {}
  param_grid:
    outer_params: &id014
      hyperopt_evals: 50
      auto_lr_find: true
      precision: 16
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 8
    batch_size: &id015
    - 1024
    - 2048
    - 4096
    attn_embed_dim_multiplier: &id016
    - 2
    - 16
    num_heads: &id017
    - 2
    - 8
    num_attn_blocks: &id018
    - 2
    - 6
    attn_dropouts: &id019
    - 0.0
    - 0.3
    embedding_dim: &id020
    - 8
    - 32
    embedding_initialization: &id021
    - kaiming_uniform
    - kaiming_normal
    embedding_bias: &id022
    - true
    - false
    share_embedding: &id023
    - true
    - false
    share_embedding_strategy: &id024
    - add
    - fraction
    shared_embedding_fraction: &id025
    - 0.25
    - 0.1
    - 0.5
    deep_layers: &id026
    - true
    - false
    layers: &id027
    - 128-64-32
    - 128-64-32-16
    - 256-128-64
    dropout: &id028
    - 0.0
    - 0.3
    activation: &id029
    - ReLU
    - LeakyReLU
    initialization: &id030
    - kaiming
    - xavier
    attention_pooling: &id031
    - true
    - false
    optimizer_fn: &id032
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id033
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: autoint
  best_params: {}
  param_grid:
    outer_params: *id014
    batch_size: *id015
    attn_embed_dim_multiplier: *id016
    num_heads: *id017
    num_attn_blocks: *id018
    attn_dropouts: *id019
    embedding_dim: *id020
    embedding_initialization: *id021
    embedding_bias: *id022
    share_embedding: *id023
    share_embedding_strategy: *id024
    shared_embedding_fraction: *id025
    deep_layers: *id026
    layers: *id027
    dropout: *id028
    activation: *id029
    initialization: *id030
    attention_pooling: *id031
    optimizer_fn: *id032
    scheduler_fn: *id033
