- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 50
      validation_fraction: 0.15
      early_stopping_rounds: 50
      verbose: false
    n_estimators: &id002
    - 100
    - 3000
    max_bin: &id003
    - 256
    - 32
    tree_method: &id004
    - auto
    - hist
    max_depth: &id005
    - 4
    - 10
    learning_rate: &id006
    - 0.1
    - 0.33
    subsample: &id007
    - 0.7
    - 1.0
    colsample_bytree: &id008
    - 0.5
    - 1.0
    min_child_weight: &id009
    - 1
    - 10
    alpha: &id010
    - 0.0
    - 5.0
    gamma: &id011
    - 0.0
    - 5.0
    lambda: &id012
    - 0.0
    - 5.0
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
