- dataset: titanic
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      max_epochs: 1
      early_stopping: true
      shuffle: true
      validation_fraction: 0.15
      early_stopping_patience: 10
    batch_size:
    - 128
    hidden_size:
    - 4096
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: gandalf
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: node
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: autoint
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: titanic
  model: tabtransformer
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      auto_lr_find: true
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: diabetes
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 1
      validation_fraction: 0.15
      early_stopping_rounds: 30
      verbose: false
    learning_rate: &id002
    - 0.3
- dataset: diabetes
  model: resnet
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 1
      max_epochs: 1000
      early_stopping: true
      early_stopping_patience: 6
      validation_fraction: 0.2
    resnet_depth:
    - resnet18
    batch_size:
    - 1024
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0
        learning_rate:
        - 0.001
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        patience:
        - 5
- dataset: diabetes
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    learning_rate: *id002
