- dataset: titanic
  model: catboost
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 32
      validation_fraction: 0.2
      early_stopping_rounds: 100
      verbose: false
    iterations: &id002
    - 200
    - 2000
    learning_rate: &id003
    - 0.001
    - 0.1
    depth: &id004
    - 4
    - 10
    colsample_bylevel: &id005
    - 0.05
    - 1.0
    l2_leaf_reg: &id006
    - 0.5
    - 5.0
    min_child_samples: &id007
    - 1
    - 100
    bagging_temperature: &id008
    - 0.1
    - 2.0
- dataset: titanic
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id009
      hyperopt_evals: 32
      validation_fraction: 0.2
      early_stopping_rounds: 30
      verbose: false
    n_estimators: &id010
    - 100
    - 5000
    max_bin: &id011
    - 256
    - 32
    tree_method: &id012
    - auto
    - hist
    max_depth: &id013
    - 4
    - 12
    learning_rate: &id014
    - 0.1
    - 0.33
    subsample: &id015
    - 0.7
    - 1.0
    colsample_bytree: &id016
    - 0.5
    - 1.0
    min_child_weight: &id017
    - 1
    - 10
    alpha: &id018
    - 0.0
    - 5.0
    gamma: &id019
    - 0.0
    - 5.0
    lambda: &id020
    - 0.0
    - 5.0
- dataset: iris
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: iris
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: adult
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: adult
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: covertype
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: housing
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: creditcard
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: bufix
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: bufix
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: heloc
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: heloc
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: breastcancer
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: breastcancer
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
- dataset: ageconditions
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    colsample_bylevel: *id005
    l2_leaf_reg: *id006
    min_child_samples: *id007
    bagging_temperature: *id008
- dataset: ageconditions
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id009
    n_estimators: *id010
    max_bin: *id011
    tree_method: *id012
    max_depth: *id013
    learning_rate: *id014
    subsample: *id015
    colsample_bytree: *id016
    min_child_weight: *id017
    alpha: *id018
    gamma: *id019
    lambda: *id020
