- dataset: titanic
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 10
    n_estimators: &id002
    - 100
    - 300
    validation_fraction: &id003
    - 0.2
    max_bin: &id004
    - 128
    - 512
    tree_method: &id005
    - auto
    max_depth: &id006
    - 4
    - 12
    learning_rate: &id007
    - 0.01
    - 0.31
    subsample: &id008
    - 0.7
    - 1.0
    colsample_bytree: &id009
    - 0.7
    - 1.0
    min_child_weight: &id010
    - 1
    - 10
    alpha: &id011
    - 0.0
    - 5.0
    gamma: &id012
    - 0.0
    - 5.0
    lambda: &id013
    - 0.0
    - 5.0
- dataset: titanic
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id014
      cv_iterations: 32
      early_stopping: true
      cv_size: 5
    hidden_layer_sizes: &id015
    - - 16
      - 16
    - - 16
      - 8
    - - 32
      - 16
    - - 45
      - 20
    activation: &id016
    - relu
    - tanh
    - logistic
    solver: &id017
    - adam
    - lbfgs
    alpha: &id018
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id019
    - 0.001
    - 0.01
    - 0.1
    beta_1: &id020
    - 0.9
    - 0.99
    - 0.8
    beta_2: &id021
    - 0.999
    - 0.9
    n_iter_no_change: &id022
    - 10
    - 20
    validation_fraction: &id023
    - 0.1
    - 0.15
    - 0.2
    max_iter: &id024
    - 100
    - 500
    batch_size: &id025
    - 32
    - 64
    - 128
    - 512
    - 1024
- dataset: titanic
  model: resnet
  best_params: {}
  param_grid:
    outer_params: &id043
      hyperopt_evals: 64
      num_epochs: 100
      early_stopping: true
    learning_rate: &id044
    - 0.0001
    - 0.001
    patience: &id045
    - 5
    - 21
    batch_size: &id046
    - 32
    - 64
    - 128
    - 256
    validation_fraction: &id047
    - 0.1
    - 0.3
    early_stopping_patience: &id048
    - 5
    - 25
    scheduler_factor: &id049
    - 0.1
    - 0.9
    scheduler_patience: &id050
    - 5
    - 10
- dataset: titanic
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: &id051
      hyperopt_evals: 32
      num_epochs: 100
      early_stopping: true
      shuffle: true
    batch_size: &id052
    - 256
    - 2048
    validation_fraction: &id053
    - 0.1
    - 0.3
    early_stopping_patience: &id054
    - 3
    - 7
    learning_rate: &id055
    - 0.01
    - 0.001
    hidden_size: &id056
    - 2048
    - 4096
    scheduler_factor: &id057
    - 0.1
    - 0.9
    scheduler_patience: &id058
    - 5
    - 10
- dataset: titanic
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id026
      max_epochs: 1000
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 10
      val_size: 0.2
      auto_lr_find: false
    early_stopping_patience: &id027
    - 5
    - 10
    virtual_batch_size_ratio: &id028
    - 0.125
    - 0.25
    - 0.5
    batch_size: &id029
    - 16
    - 32
    - 64
    - 128
    - 256
    weights: &id030
    - 0
    - 1
    mask_type: &id031
    - sparsemax
    - entmax
    n_d: &id032
    - 8
    - 16
    n_steps: &id033
    - 3
    - 10
    gamma: &id034
    - 1.0
    - 2.0
    cat_emb_dim: &id035
    - 1
    - 3
    n_independent: &id036
    - 1
    - 5
    n_shared: &id037
    - 1
    - 5
    lambda_sparse: &id038
    - 0.001
    - 0.01
    momentum: &id039
    - 0.001
    - 0.4
    clip_value: &id040
    - 1
    - 2
    optimizer_fn: &id041
      Adam:
        lr:
        - 0.001
        weight_decay:
        - 0.0001
    scheduler_fn: &id042
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 5
        - 10
- dataset: titanic
  model: gate
  best_params: {}
  param_grid:
    outer_params: &id059
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 300
      val_size: 0.2
    early_stopping_patience: &id060
    - 5
    - 10
    batch_size: &id061
    - 16
    - 32
    - 64
    - 128
    - 256
    tree_depth: &id062
    - 4
    - 12
    num_trees: &id063
    - 6
    - 16
    chain_trees: &id064
    - true
    - false
    gflu_stages: &id065
    - 2
    - 4
    optimizer_fn: &id066
      Adam:
        lr:
        - 0.001
        weight_decay:
        - 0.0001
    scheduler_fn: &id067
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 5
        - 10
- dataset: titanic
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: &id068
      max_epochs: 300
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 10
      val_size: 0.2
      auto_lr_find: false
    early_stopping_patience: &id069
    - 5
    - 10
    batch_size: &id070
    - 16
    - 32
    - 64
    - 128
    - 256
    learning_rate: &id071
    - 0.001
    - 0.0001
    optimizer_fn: &id072
      Adam:
        lr:
        - 0.001
        - 0.0001
        weight_decay:
        - 0.0001
        - 0.3
    scheduler_fn: &id073
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 9
- dataset: titanic
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: &id074
      max_epochs: 300
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 10
      val_size: 0.2
      auto_lr_find: false
    early_stopping_patience: &id075
    - 5
    - 10
    batch_size: &id076
    - 16
    - 32
    - 64
    - 128
    - 256
    input_embed_dim: &id077
    - 16
    - 32
    - 64
    embedding_initialization: &id078
    - kaiming_uniform
    - kaiming_normal
    embedding_bias: &id079
    - true
    - false
    share_embedding: &id080
    - true
    - false
    share_embedding_strategy: &id081
    - add
    - fraction
    - add
    shared_embedding_fraction: &id082
    - 0.1
    - 0.25
    - 0.5
    attn_feature_importance: &id083
    - true
    - false
    num_heads: &id084
    - 6
    - 8
    - 10
    num_attn_blocks: &id085
    - 4
    - 6
    - 8
    transformer_head_dim: &id086
    - 64
    - 128
    attn_dropout: &id087
    - 0.05
    - 0.1
    - 0.15
    add_norm_dropout: &id088
    - 0.05
    - 0.1
    - 0.15
    ff_dropout: &id089
    - 0.05
    - 0.1
    - 0.15
    ff_hidden_multiplier: &id090
    - 3
    - 4
    - 5
    transformer_activation: &id091
    - ReLU
    - GEGLU
    - SwiGLU
    embedding_dropout: &id092
    - 0.05
    - 0.1
    - 0.15
    batch_norm_continuous_input: &id093
    - false
    - true
    learning_rate: &id094
    - 0.0005
    - 0.001
    - 0.002
    optimizer_fn: &id095
      Adam:
        lr:
        - 0.001
        - 0.0001
        weight_decay:
        - 0.0001
        - 0.3
    scheduler_fn: &id096
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 9
- dataset: titanic
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: &id097
      max_epochs: 300
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 10
      val_size: 0.2
      auto_lr_find: false
    early_stopping_patience: &id098
    - 5
    - 10
    batch_size: &id099
    - 16
    - 32
    - 64
    - 128
    - 256
    optimizer_fn: &id100
      Adam:
        lr:
        - 0.001
        - 0.0001
        weight_decay:
        - 0.0001
        - 0.3
    scheduler_fn: &id101
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 9
- dataset: titanic
  model: node
  best_params: {}
  param_grid:
    outer_params: &id102
      max_epochs: 300
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 10
      val_size: 0.2
      auto_lr_find: false
    early_stopping_patience: &id103
    - 5
    - 10
    batch_size: &id104
    - 16
    - 32
    - 64
    - 128
    - 256
    optimizer_fn: &id105
      Adam:
        lr:
        - 0.001
        - 0.0001
        weight_decay:
        - 0.0001
        - 0.3
    scheduler_fn: &id106
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 9
- dataset: iris
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    validation_fraction: *id003
    max_bin: *id004
    tree_method: *id005
    max_depth: *id006
    learning_rate: *id007
    subsample: *id008
    colsample_bytree: *id009
    min_child_weight: *id010
    alpha: *id011
    gamma: *id012
    lambda: *id013
- dataset: iris
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id014
    hidden_layer_sizes: *id015
    activation: *id016
    solver: *id017
    alpha: *id018
    learning_rate_init: *id019
    beta_1: *id020
    beta_2: *id021
    n_iter_no_change: *id022
    validation_fraction: *id023
    max_iter: *id024
    batch_size: *id025
- dataset: iris
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id026
    early_stopping_patience: *id027
    virtual_batch_size_ratio: *id028
    batch_size: *id029
    weights: *id030
    mask_type: *id031
    n_d: *id032
    n_steps: *id033
    gamma: *id034
    cat_emb_dim: *id035
    n_independent: *id036
    n_shared: *id037
    lambda_sparse: *id038
    momentum: *id039
    clip_value: *id040
    optimizer_fn: *id041
    scheduler_fn: *id042
- dataset: iris
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id043
    learning_rate: *id044
    patience: *id045
    batch_size: *id046
    validation_fraction: *id047
    early_stopping_patience: *id048
    scheduler_factor: *id049
    scheduler_patience: *id050
- dataset: iris
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id051
    batch_size: *id052
    validation_fraction: *id053
    early_stopping_patience: *id054
    learning_rate: *id055
    hidden_size: *id056
    scheduler_factor: *id057
    scheduler_patience: *id058
- dataset: iris
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id059
    early_stopping_patience: *id060
    batch_size: *id061
    tree_depth: *id062
    num_trees: *id063
    chain_trees: *id064
    gflu_stages: *id065
    optimizer_fn: *id066
    scheduler_fn: *id067
- dataset: iris
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: *id068
    early_stopping_patience: *id069
    batch_size: *id070
    learning_rate: *id071
    optimizer_fn: *id072
    scheduler_fn: *id073
- dataset: iris
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id074
    early_stopping_patience: *id075
    batch_size: *id076
    input_embed_dim: *id077
    embedding_initialization: *id078
    embedding_bias: *id079
    share_embedding: *id080
    share_embedding_strategy: *id081
    shared_embedding_fraction: *id082
    attn_feature_importance: *id083
    num_heads: *id084
    num_attn_blocks: *id085
    transformer_head_dim: *id086
    attn_dropout: *id087
    add_norm_dropout: *id088
    ff_dropout: *id089
    ff_hidden_multiplier: *id090
    transformer_activation: *id091
    embedding_dropout: *id092
    batch_norm_continuous_input: *id093
    learning_rate: *id094
    optimizer_fn: *id095
    scheduler_fn: *id096
- dataset: iris
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: *id097
    early_stopping_patience: *id098
    batch_size: *id099
    optimizer_fn: *id100
    scheduler_fn: *id101
- dataset: iris
  model: node
  best_params: {}
  param_grid:
    outer_params: *id102
    early_stopping_patience: *id103
    batch_size: *id104
    optimizer_fn: *id105
    scheduler_fn: *id106
- dataset: breastcancer
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    validation_fraction: *id003
    max_bin: *id004
    tree_method: *id005
    max_depth: *id006
    learning_rate: *id007
    subsample: *id008
    colsample_bytree: *id009
    min_child_weight: *id010
    alpha: *id011
    gamma: *id012
    lambda: *id013
- dataset: breastcancer
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id074
    early_stopping_patience: *id075
    batch_size: *id076
    input_embed_dim: *id077
    embedding_initialization: *id078
    embedding_bias: *id079
    share_embedding: *id080
    share_embedding_strategy: *id081
    shared_embedding_fraction: *id082
    attn_feature_importance: *id083
    num_heads: *id084
    num_attn_blocks: *id085
    transformer_head_dim: *id086
    attn_dropout: *id087
    add_norm_dropout: *id088
    ff_dropout: *id089
    ff_hidden_multiplier: *id090
    transformer_activation: *id091
    embedding_dropout: *id092
    batch_norm_continuous_input: *id093
    learning_rate: *id094
    optimizer_fn: *id095
    scheduler_fn: *id096
- dataset: breastcancer
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id014
    hidden_layer_sizes: *id015
    activation: *id016
    solver: *id017
    alpha: *id018
    learning_rate_init: *id019
    beta_1: *id020
    beta_2: *id021
    n_iter_no_change: *id022
    validation_fraction: *id023
    max_iter: *id024
    batch_size: *id025
- dataset: breastcancer
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id026
    early_stopping_patience: *id027
    virtual_batch_size_ratio: *id028
    batch_size: *id029
    weights: *id030
    mask_type: *id031
    n_d: *id032
    n_steps: *id033
    gamma: *id034
    cat_emb_dim: *id035
    n_independent: *id036
    n_shared: *id037
    lambda_sparse: *id038
    momentum: *id039
    clip_value: *id040
    optimizer_fn: *id041
    scheduler_fn: *id042
- dataset: breastcancer
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id043
    learning_rate: *id044
    patience: *id045
    batch_size: *id046
    validation_fraction: *id047
    early_stopping_patience: *id048
    scheduler_factor: *id049
    scheduler_patience: *id050
- dataset: breastcancer
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id051
    batch_size: *id052
    validation_fraction: *id053
    early_stopping_patience: *id054
    learning_rate: *id055
    hidden_size: *id056
    scheduler_factor: *id057
    scheduler_patience: *id058
- dataset: breastcancer
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id059
    early_stopping_patience: *id060
    batch_size: *id061
    tree_depth: *id062
    num_trees: *id063
    chain_trees: *id064
    gflu_stages: *id065
    optimizer_fn: *id066
    scheduler_fn: *id067
- dataset: breastcancer
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: *id068
    early_stopping_patience: *id069
    batch_size: *id070
    learning_rate: *id071
    optimizer_fn: *id072
    scheduler_fn: *id073
- dataset: breastcancer
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: *id097
    early_stopping_patience: *id098
    batch_size: *id099
    optimizer_fn: *id100
    scheduler_fn: *id101
- dataset: breastcancer
  model: node
  best_params: {}
  param_grid:
    outer_params: *id102
    early_stopping_patience: *id103
    batch_size: *id104
    optimizer_fn: *id105
    scheduler_fn: *id106
