- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 10
      validation_fraction: 0.15
      early_stopping_rounds: 30
      verbose: false
    n_estimators: &id002
    - 100
    - 5000
    max_bin: &id003
    - 256
    - 32
    tree_method: &id004
    - auto
    - hist
    max_depth: &id005
    - 4
    - 10
    learning_rate: &id006
    - 0.1
    - 0.33
    subsample: &id007
    - 0.7
    - 1.0
    colsample_bytree: &id008
    - 0.5
    - 1.0
    min_child_weight: &id009
    - 1
    - 10
    alpha: &id010
    - 0.0
    - 5.0
    gamma: &id011
    - 0.0
    - 5.0
    lambda: &id012
    - 0.0
    - 5.0
- dataset: housing
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id013
      cv_iterations: 10
      early_stopping: true
      cv_size: 5
      validation_fraction: 0.15
      n_iter_no_change: 6
      max_iter: 1000
    hidden_layer_sizes: &id014
    - - 16
      - 32
    - - 16
      - 8
    - - 32
      - 16
    - - 128
      - 64
      - 32
    activation: &id015
    - relu
    - tanh
    - logistic
    solver: &id016
    - adam
    - lbfgs
    alpha: &id017
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id018
    - 0.001
    - 0.01
    - 0.1
    beta_1: &id019
    - 0.9
    - 0.99
    - 0.8
    beta_2: &id020
    - 0.999
    - 0.9
    batch_size: &id021
    - 512
    - 1024
    - 2048
    - 4096
- dataset: housing
  model: gate
  best_params: {}
  param_grid:
    outer_params: &id022
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id023
    - 0.001
    - 0.0001
    batch_size: &id024
    - 512
    - 1024
    - 2048
    - 4096
    tree_depth: &id025
    - 4
    - 7
    num_trees: &id026
    - 4
    - 12
    chain_trees: &id027
    - false
    - true
    gflu_stages: &id028
    - 2
    - 4
    optimizer_fn: &id029
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id030
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: housing
  model: node
  best_params: {}
  param_grid:
    outer_params: &id031
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id032
    - 0.01
    - 0.0001
    batch_size: &id033
    - 512
    - 1024
    - 2048
    - 4096
    num_trees: &id034
    - 1024
    - 2048
    - 4096
    additional_tree_output_dim: &id035
    - 2
    - 3
    - 4
    depth: &id036
    - 7
    choice_function: &id037
    - entmax15
    - sparsemax
    bin_function: &id038
    - entmoid15
    - sparsemoid
    input_dropout: &id039
    - 0.0
    - 0.3
    embed_categorical: &id040
    - true
    - false
    optimizer_fn: &id041
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id042
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: covertype
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id013
    hidden_layer_sizes: *id014
    activation: *id015
    solver: *id016
    alpha: *id017
    learning_rate_init: *id018
    beta_1: *id019
    beta_2: *id020
    batch_size: *id021
- dataset: covertype
  model: resnet18
  best_params: {}
  param_grid:
    outer_params: &id043
      hyperopt_evals: 10
      num_epochs: 1000
      early_stopping: true
      early_stopping_patience: 6
      validation_fraction: 0.15
    learning_rate: &id044
    - 0.0001
    - 0.001
    batch_size: &id045
    - 512
    - 1024
    - 2048
    - 4096
    scheduler_factor: &id046
    - 0.1
    - 0.9
    scheduler_patience: &id047
    - 3
    - 5
- dataset: covertype
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: &id048
      hyperopt_evals: 10
      num_epochs: 1000
      early_stopping: true
      shuffle: true
      validation_fraction: 0.15
      early_stopping_patience: 6
    batch_size: &id049
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id050
    - 0.01
    - 0.0001
    hidden_size: &id051
    - 1024
    - 2048
    - 4096
    scheduler_factor: &id052
    - 0.1
    - 0.9
    scheduler_patience: &id053
    - 4
    - 7
- dataset: covertype
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id054
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id055
    - 0.001
    - 0.0001
    virtual_batch_size_ratio: &id056
    - 0.125
    - 0.25
    - 0.5
    - 1.0
    batch_size: &id057
    - 512
    - 1024
    - 2048
    - 4096
    weights: &id058
    - 0
    - 1
    mask_type: &id059
    - sparsemax
    - entmax
    n_d: &id060
    - 8
    - 32
    n_steps: &id061
    - 3
    - 5
    gamma: &id062
    - 1.0
    - 2.0
    n_independent: &id063
    - 2
    - 3
    lambda_sparse: &id064
    - 1.0e-05
    - 0.001
    n_shared: &id065
    - 2
    - 3
    optimizer_fn: &id066
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id067
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id022
    learning_rate: *id023
    batch_size: *id024
    tree_depth: *id025
    num_trees: *id026
    chain_trees: *id027
    gflu_stages: *id028
    optimizer_fn: *id029
    scheduler_fn: *id030
- dataset: covertype
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: &id068
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id069
    - 0.001
    - 0.0001
    batch_size: &id070
    - 512
    - 1024
    - 2048
    - 4096
    embedding_initialization: &id071
    - kaiming_uniform
    - kaiming_normal
    shared_embedding_fraction: &id072
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks: &id073
    - 4
    - 10
    attn_dropout: &id074
    - 0.05
    - 0.3
    add_norm_dropout: &id075
    - 0.05
    - 0.3
    ff_dropout: &id076
    - 0.05
    - 0.3
    ff_hidden_multiplier: &id077
    - 2
    - 6
    transformer_activation: &id078
    - GEGLU
    - ReGLU
    - SwiGLU
    embedding_dropout: &id079
    - 0.05
    - 0.3
    optimizer_fn: &id080
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id081
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: &id082
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
      precision: 16
    batch_size: &id083
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id084
    - 0.001
    - 0.0001
    layers: &id085
    - 128-64-32
    - 64-32-16
    - 512-128-32
    activation: &id086
    - ReLU
    - LeakyReLU
    initialization: &id087
    - kaiming
    - xavier
    dropout: &id088
    - 0.0
    - 0.3
    optimizer_fn: &id089
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id090
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: &id091
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    learning_rate: &id092
    - 0.001
    - 0.0001
    batch_size: &id093
    - 512
    - 1024
    - 2048
    - 4096
    gflu_stages: &id094
    - 2
    - 8
    gflu_dropout: &id095
    - 0.0
    - 0.3
    embedding_dropout: &id096
    - 0.0
    - 0.3
    optimizer_fn: &id097
      Adam:
        weight_decay:
        - 0.0
        - 0.01
      AdamW:
        weight_decay:
        - 0.0
        - 0.01
    scheduler_fn: &id098
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 10
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: node
  best_params: {}
  param_grid:
    outer_params: *id031
    learning_rate: *id032
    batch_size: *id033
    num_trees: *id034
    additional_tree_output_dim: *id035
    depth: *id036
    choice_function: *id037
    bin_function: *id038
    input_dropout: *id039
    embed_categorical: *id040
    optimizer_fn: *id041
    scheduler_fn: *id042
- dataset: covertype
  model: autoint
  best_params: {}
  param_grid:
    outer_params: &id099
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id100
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id101
    - 0.001
    - 0.0001
    num_attn_blocks: &id102
    - 3
    - 2
    - 4
    attn_dropouts: &id103
    - 0.0
    - 0.1
    - 0.3
    has_residuals: &id104
    - true
    - false
    embedding_initialization: &id105
    - kaiming_uniform
    - kaiming_normal
    embedding_bias: &id106
    - true
    - false
    share_embedding: &id107
    - true
    - false
    share_embedding_strategy: &id108
    - add
    - fraction
    shared_embedding_fraction: &id109
    - 0.25
    - 0.1
    - 0.5
    deep_layers: &id110
    - true
    - false
    layers: &id111
    - 128-64-32
    - 64-32
    - 256-128-64
    activation: &id112
    - ReLU
    - LeakyReLU
    - Tanh
    initialization: &id113
    - kaiming
    - xavier
    - random
    dropout: &id114
    - 0.0
    - 0.2
    - 0.0
    attention_pooling: &id115
    - true
    - false
    optimizer_fn: &id116
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id117
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: tabtransformer
  best_params: {}
  param_grid:
    outer_params: &id118
      hyperopt_evals: 10
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 6
    batch_size: &id119
    - 512
    - 1024
    - 2048
    - 4096
    learning_rate: &id120
    - 0.01
    - 0.0001
    embedding_bias: &id121
    - true
    - false
    embedding_initialization: &id122
    - kaiming_uniform
    - kaiming_normal
    shared_embedding_fraction: &id123
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks: &id124
    - 4
    - 10
    attn_dropout: &id125
    - 0.05
    - 0.3
    add_norm_dropout: &id126
    - 0.05
    - 0.3
    ff_dropout: &id127
    - 0.05
    - 0.3
    ff_hidden_multiplier: &id128
    - 2
    - 6
    transformer_activation: &id129
    - GEGLU
    - ReGLU
    - SwiGLU
    embedding_dropout: &id130
    - 0.05
    - 0.3
    optimizer_fn: &id131
      Adam:
        weight_decay:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 0.0001
        - 0.01
    scheduler_fn: &id132
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 4
        - 7
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
      StepLR:
        step_size:
        - 5
        - 30
        gamma:
        - 0.9
        - 0.99
- dataset: covertype
  model: catboost
  best_params: {}
  param_grid:
    outer_params: &id133
      hyperopt_evals: 10
      validation_fraction: 0.15
      early_stopping_rounds: 100
      verbose: false
    iterations: &id134
    - 200
    - 2000
    learning_rate: &id135
    - 0.001
    - 0.1
    depth: &id136
    - 4
    - 10
    l2_leaf_reg: &id137
    - 0.5
    - 5.0
    min_child_samples: &id138
    - 1
    - 100
    bagging_temperature: &id139
    - 0.1
    - 2.0
- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: creditcard
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id013
    hidden_layer_sizes: *id014
    activation: *id015
    solver: *id016
    alpha: *id017
    learning_rate_init: *id018
    beta_1: *id019
    beta_2: *id020
    batch_size: *id021
- dataset: creditcard
  model: resnet18
  best_params: {}
  param_grid:
    outer_params: *id043
    learning_rate: *id044
    batch_size: *id045
    scheduler_factor: *id046
    scheduler_patience: *id047
- dataset: creditcard
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id048
    batch_size: *id049
    learning_rate: *id050
    hidden_size: *id051
    scheduler_factor: *id052
    scheduler_patience: *id053
- dataset: creditcard
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id054
    learning_rate: *id055
    virtual_batch_size_ratio: *id056
    batch_size: *id057
    weights: *id058
    mask_type: *id059
    n_d: *id060
    n_steps: *id061
    gamma: *id062
    n_independent: *id063
    lambda_sparse: *id064
    n_shared: *id065
    optimizer_fn: *id066
    scheduler_fn: *id067
- dataset: creditcard
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id022
    learning_rate: *id023
    batch_size: *id024
    tree_depth: *id025
    num_trees: *id026
    chain_trees: *id027
    gflu_stages: *id028
    optimizer_fn: *id029
    scheduler_fn: *id030
- dataset: creditcard
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id068
    learning_rate: *id069
    batch_size: *id070
    embedding_initialization: *id071
    shared_embedding_fraction: *id072
    num_attn_blocks: *id073
    attn_dropout: *id074
    add_norm_dropout: *id075
    ff_dropout: *id076
    ff_hidden_multiplier: *id077
    transformer_activation: *id078
    embedding_dropout: *id079
    optimizer_fn: *id080
    scheduler_fn: *id081
- dataset: creditcard
  model: categoryembedding
  best_params: {}
  param_grid:
    outer_params: *id082
    batch_size: *id083
    learning_rate: *id084
    layers: *id085
    activation: *id086
    initialization: *id087
    dropout: *id088
    optimizer_fn: *id089
    scheduler_fn: *id090
- dataset: creditcard
  model: gandalf
  best_params: {}
  param_grid:
    outer_params: *id091
    learning_rate: *id092
    batch_size: *id093
    gflu_stages: *id094
    gflu_dropout: *id095
    embedding_dropout: *id096
    optimizer_fn: *id097
    scheduler_fn: *id098
- dataset: creditcard
  model: node
  best_params: {}
  param_grid:
    outer_params: *id031
    learning_rate: *id032
    batch_size: *id033
    num_trees: *id034
    additional_tree_output_dim: *id035
    depth: *id036
    choice_function: *id037
    bin_function: *id038
    input_dropout: *id039
    embed_categorical: *id040
    optimizer_fn: *id041
    scheduler_fn: *id042
- dataset: creditcard
  model: autoint
  best_params: {}
  param_grid:
    outer_params: *id099
    batch_size: *id100
    learning_rate: *id101
    num_attn_blocks: *id102
    attn_dropouts: *id103
    has_residuals: *id104
    embedding_initialization: *id105
    embedding_bias: *id106
    share_embedding: *id107
    share_embedding_strategy: *id108
    shared_embedding_fraction: *id109
    deep_layers: *id110
    layers: *id111
    activation: *id112
    initialization: *id113
    dropout: *id114
    attention_pooling: *id115
    optimizer_fn: *id116
    scheduler_fn: *id117
- dataset: creditcard
  model: tabtransformer
  best_params: {}
  param_grid:
    outer_params: *id118
    batch_size: *id119
    learning_rate: *id120
    embedding_bias: *id121
    embedding_initialization: *id122
    shared_embedding_fraction: *id123
    num_attn_blocks: *id124
    attn_dropout: *id125
    add_norm_dropout: *id126
    ff_dropout: *id127
    ff_hidden_multiplier: *id128
    transformer_activation: *id129
    embedding_dropout: *id130
    optimizer_fn: *id131
    scheduler_fn: *id132
- dataset: creditcard
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id133
    iterations: *id134
    learning_rate: *id135
    depth: *id136
    l2_leaf_reg: *id137
    min_child_samples: *id138
    bagging_temperature: *id139
