- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 5
      validation_fraction: 0.15
      early_stopping_rounds: 50
      verbose: false
    n_estimators:
    - 100
    - 4000
    max_bin:
    - 256
    - 32
    max_depth:
    - 4
    - 9
    learning_rate:
    - 0.1
    - 0.33
    subsample:
    - 0.7
    - 1.0
    colsample_bytree:
    - 0.5
    - 1.0
    min_child_weight:
    - 1
    - 10
    alpha:
    - 0.0
    - 5.0
    gamma:
    - 0.0
    - 5.0
    lambda:
    - 0.0
    - 5.0
- dataset: creditcard
  model: gate
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 5
      auto_lr_find: true
      precision: 16
      tol: 1.0e-06
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 3
    batch_size: &id002
    - 2048
    - 4096
    tree_depth: &id003
    - 4
    - 6
    num_trees: &id004
    - 4
    - 8
    gflu_stages: &id005
    - 3
    - 8
    gflu_dropout: &id006
    - 0.0
    - 0.05
    tree_dropout: &id007
    - 0.0
    - 0.05
    tree_wise_attention_dropout: &id008
    - 0.0
    - 0.05
    embedding_dropout: &id009
    - 0
    - 0.2
    optimizer_fn: &id010
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id011
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: creditcard
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params:
      hyperopt_evals: 5
      auto_lr_find: true
      precision: 16
      tol: 1.0e-06
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 3
      attn_feature_importance: false
    batch_size:
    - 1024
    - 2048
    num_heads:
    - 4
    - 6
    input_embed_dim_multiplier:
    - 2
    - 4
    embedding_initialization:
    - kaiming_uniform
    - kaiming_normal
    embedding_dropout:
    - 0.05
    - 0.2
    shared_embedding_fraction:
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks:
    - 4
    - 6
    attn_dropout:
    - 0.05
    - 0.2
    add_norm_dropout:
    - 0.05
    - 0.2
    ff_dropout:
    - 0.05
    - 0.2
    ff_hidden_multiplier:
    - 4
    - 32
    transformer_activation:
    - GEGLU
    - ReGLU
    - SwiGLU
    optimizer_fn:
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn:
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: diabetes
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    tree_depth: *id003
    num_trees: *id004
    gflu_stages: *id005
    gflu_dropout: *id006
    tree_dropout: *id007
    tree_wise_attention_dropout: *id008
    embedding_dropout: *id009
    optimizer_fn: *id010
    scheduler_fn: *id011
- dataset: covertype
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    tree_depth: *id003
    num_trees: *id004
    gflu_stages: *id005
    gflu_dropout: *id006
    tree_dropout: *id007
    tree_wise_attention_dropout: *id008
    embedding_dropout: *id009
    optimizer_fn: *id010
    scheduler_fn: *id011
