- dataset: ageconditions
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id013
      hyperopt_evals: 50
      validation_fraction: 0.15
      early_stopping_rounds: 10
      verbose: false
    n_estimators: &id014
    - 100
    - 2000
    max_bin: &id015
    - 256
    - 32
    tree_method: &id016
    - auto
    - hist
    max_depth: &id017
    - 4
    - 10
    learning_rate: &id018
    - 0.1
    - 0.33
    subsample: &id019
    - 0.7
    - 1.0
    colsample_bytree: &id020
    - 0.5
    - 1.0
    min_child_weight: &id021
    - 1
    - 10
    alpha: &id022
    - 0.0
    - 5.0
    gamma: &id023
    - 0.0
    - 5.0
    lambda: &id024
    - 0.0
    - 5.0
- dataset: adult
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 50
      validation_fraction: 0.15
      early_stopping_rounds: 10
      verbose: false
    n_estimators: &id002
    - 100
    - 1500
    max_bin: &id003
    - 256
    - 32
    tree_method: &id004
    - auto
    - hist
    max_depth: &id005
    - 4
    - 10
    learning_rate: &id006
    - 0.1
    - 0.33
    subsample: &id007
    - 0.7
    - 1.0
    colsample_bytree: &id008
    - 0.5
    - 1.0
    min_child_weight: &id009
    - 1
    - 10
    alpha: &id010
    - 0.0
    - 5.0
    gamma: &id011
    - 0.0
    - 5.0
    lambda: &id012
    - 0.0
    - 5.0
- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: breastcancer
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id013
    n_estimators: *id014
    max_bin: *id015
    tree_method: *id016
    max_depth: *id017
    learning_rate: *id018
    subsample: *id019
    colsample_bytree: *id020
    min_child_weight: *id021
    alpha: *id022
    gamma: *id023
    lambda: *id024
- dataset: titanic
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id013
    n_estimators: *id014
    max_bin: *id015
    tree_method: *id016
    max_depth: *id017
    learning_rate: *id018
    subsample: *id019
    colsample_bytree: *id020
    min_child_weight: *id021
    alpha: *id022
    gamma: *id023
    lambda: *id024
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: iris
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id013
    n_estimators: *id014
    max_bin: *id015
    tree_method: *id016
    max_depth: *id017
    learning_rate: *id018
    subsample: *id019
    colsample_bytree: *id020
    min_child_weight: *id021
    alpha: *id022
    gamma: *id023
    lambda: *id024
- dataset: diabetes
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
- dataset: heloc
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    max_bin: *id003
    tree_method: *id004
    max_depth: *id005
    learning_rate: *id006
    subsample: *id007
    colsample_bytree: *id008
    min_child_weight: *id009
    alpha: *id010
    gamma: *id011
    lambda: *id012
