- dataset: titanic
  model: catboost
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 32
      validation_fraction: 0.2
      early_stopping_rounds: 30
      verbose: false
    iterations: &id002
    - 500
    - 100
    - 5000
    learning_rate: &id003
    - 0.1
    - 0.01
    - 0.3
    depth: &id004
    - 6
    - 4
    - 12
    l2_leaf_reg: &id005
    - 3.0
    - 0.1
    - 10.0
    border_count: &id006
    - 254
    - 32
    - 512
    bagging_temperature: &id007
    - 1.0
    - 0.5
    - 2.0
    random_strength: &id008
    - 1.0
    - 0.0
    - 2.0
    scale_pos_weight: &id009
    - 1.0
    - 0.5
    - 2.0
    colsample_bylevel: &id010
    - 0.05
    - 1.0
    min_data_in_leaf: &id011
    - 1
    - 100
- dataset: titanic
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id012
      hyperopt_evals: 32
      validation_fraction: 0.2
      early_stopping_rounds: 30
      verbose: false
    n_estimators: &id013
    - 100
    - 5000
    max_bin: &id014
    - 256
    - 32
    tree_method: &id015
    - auto
    - hist
    max_depth: &id016
    - 4
    - 12
    learning_rate: &id017
    - 0.1
    - 0.33
    subsample: &id018
    - 0.7
    - 1.0
    colsample_bytree: &id019
    - 0.5
    - 1.0
    min_child_weight: &id020
    - 1
    - 10
    alpha: &id021
    - 0.0
    - 5.0
    gamma: &id022
    - 0.0
    - 5.0
    lambda: &id023
    - 0.0
    - 5.0
- dataset: iris
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: iris
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: adult
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: adult
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: covertype
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: covertype
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: housing
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: creditcard
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: creditcard
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: bufix
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: bufix
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: heloc
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: heloc
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: breastcancer
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: breastcancer
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
- dataset: ageconditions
  model: catboost
  best_params: {}
  param_grid:
    outer_params: *id001
    iterations: *id002
    learning_rate: *id003
    depth: *id004
    l2_leaf_reg: *id005
    border_count: *id006
    bagging_temperature: *id007
    random_strength: *id008
    scale_pos_weight: *id009
    colsample_bylevel: *id010
    min_data_in_leaf: *id011
- dataset: ageconditions
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id012
    n_estimators: *id013
    max_bin: *id014
    tree_method: *id015
    max_depth: *id016
    learning_rate: *id017
    subsample: *id018
    colsample_bytree: *id019
    min_child_weight: *id020
    alpha: *id021
    gamma: *id022
    lambda: *id023
