- dataset: iris
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 50
      max_epochs: 1000
      early_stopping: true
      shuffle: true
      validation_fraction: 0.15
      early_stopping_patience: 10
    batch_size: &id002
    - 32
    - 64
    - 128
    - 256
    hidden_size: &id003
    - 1024
    - 2048
    - 4096
    optimizer_fn: &id004
      Adam:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.01
      AdamW:
        weight_decay:
        - 1.0e-05
        - 0.001
        learning_rate:
        - 0.0001
        - 0.01
    scheduler_fn: &id005
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: titanic
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    hidden_size: *id003
    optimizer_fn: *id004
    scheduler_fn: *id005
- dataset: ageconditions
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    hidden_size: *id003
    optimizer_fn: *id004
    scheduler_fn: *id005
- dataset: ageconditions
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: &id006
      hyperopt_evals: 50
      auto_lr_find: true
      precision: 16
      max_epochs: 1000
      val_size: 0.15
      early_stopping_patience: 10
      attn_feature_importance: false
    batch_size: &id007
    - 32
    - 64
    - 128
    - 256
    num_heads: &id008
    - 4
    - 10
    input_embed_dim_multiplier: &id009
    - 2
    - 6
    embedding_initialization: &id010
    - kaiming_uniform
    - kaiming_normal
    embedding_dropout: &id011
    - 0.05
    - 0.2
    shared_embedding_fraction: &id012
    - 0.125
    - 0.25
    - 0.5
    num_attn_blocks: &id013
    - 4
    - 8
    attn_dropout: &id014
    - 0.05
    - 0.2
    add_norm_dropout: &id015
    - 0.05
    - 0.2
    ff_dropout: &id016
    - 0.05
    - 0.2
    ff_hidden_multiplier: &id017
    - 4
    - 32
    transformer_activation: &id018
    - GEGLU
    - ReGLU
    - SwiGLU
    optimizer_fn: &id019
      Adam:
        weight_decay:
        - 0.0001
        - 1.0e-05
      AdamW:
        weight_decay:
        - 0.0001
        - 1.0e-05
    scheduler_fn: &id020
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 3
        - 5
      ExponentialLR:
        gamma:
        - 0.9
        - 0.99
- dataset: iris
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id006
    batch_size: *id007
    num_heads: *id008
    input_embed_dim_multiplier: *id009
    embedding_initialization: *id010
    embedding_dropout: *id011
    shared_embedding_fraction: *id012
    num_attn_blocks: *id013
    attn_dropout: *id014
    add_norm_dropout: *id015
    ff_dropout: *id016
    ff_hidden_multiplier: *id017
    transformer_activation: *id018
    optimizer_fn: *id019
    scheduler_fn: *id020
- dataset: breastcancer
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id001
    batch_size: *id002
    hidden_size: *id003
    optimizer_fn: *id004
    scheduler_fn: *id005
- dataset: breastcancer
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id006
    batch_size: *id007
    num_heads: *id008
    input_embed_dim_multiplier: *id009
    embedding_initialization: *id010
    embedding_dropout: *id011
    shared_embedding_fraction: *id012
    num_attn_blocks: *id013
    attn_dropout: *id014
    add_norm_dropout: *id015
    ff_dropout: *id016
    ff_hidden_multiplier: *id017
    transformer_activation: *id018
    optimizer_fn: *id019
    scheduler_fn: *id020
- dataset: titanic
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id006
    batch_size: *id007
    num_heads: *id008
    input_embed_dim_multiplier: *id009
    embedding_initialization: *id010
    embedding_dropout: *id011
    shared_embedding_fraction: *id012
    num_attn_blocks: *id013
    attn_dropout: *id014
    add_norm_dropout: *id015
    ff_dropout: *id016
    ff_hidden_multiplier: *id017
    transformer_activation: *id018
    optimizer_fn: *id019
    scheduler_fn: *id020
