- dataset: titanic
  model: xgb
  best_params: {}
  param_grid:
    outer_params: &id001
      hyperopt_evals: 2
    n_estimators: &id002
    - 100
    - 1500
    validation_fraction: &id003
    - 0.1
    - 0.25
    max_bin: &id004
    - 256
    - 32
    tree_method: &id005
    - auto
    - hist
    max_depth: &id006
    - 4
    - 12
    learning_rate: &id007
    - 0.1
    - 0.33
    subsample: &id008
    - 0.7
    - 1.0
    colsample_bytree: &id009
    - 0.5
    - 1.0
    min_child_weight: &id010
    - 1
    - 10
    alpha: &id011
    - 0.0
    - 5.0
    gamma: &id012
    - 0.0
    - 5.0
    lambda: &id013
    - 0.0
    - 5.0
- dataset: titanic
  model: mlp
  best_params: {}
  param_grid:
    outer_params: &id014
      cv_iterations: 2
      early_stopping: true
      cv_size: 4
    hidden_layer_sizes: &id015
    - - 8
    - - 16
      - 8
    activation: &id016
    - relu
    - tanh
    - logistic
    solver: &id017
    - adam
    - lbfgs
    alpha: &id018
    - 0.0001
    - 0.001
    - 0.01
    learning_rate_init: &id019
    - 0.001
    - 0.01
    - 0.1
    beta_1: &id020
    - 0.9
    - 0.99
    - 0.8
    beta_2: &id021
    - 0.999
    - 0.9
    n_iter_no_change: &id022
    - 10
    - 20
    validation_fraction: &id023
    - 0.1
    - 0.15
    - 0.2
    max_iter: &id024
    - 1000
    - 5000
    batch_size: &id025
    - 16
    - 32
    - 64
    - 128
- dataset: titanic
  model: resnet
  best_params: {}
  param_grid:
    outer_params: &id026
      hyperopt_evals: 2
      num_epochs: 2
      early_stopping: true
    learning_rate: &id027
    - 0.0001
    - 0.001
    batch_size: &id028
    - 16
    - 32
    - 64
    - 128
    validation_fraction: &id029
    - 0.1
    - 0.2
    - 0.3
    early_stopping_patience: &id030
    - 10
    - 20
    scheduler_factor: &id031
    - 0.1
    - 0.9
    scheduler_patience: &id032
    - 10
    - 15
    - 20
- dataset: titanic
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: &id033
      hyperopt_evals: 2
      num_epochs: 1000
      early_stopping: true
      shuffle: true
    batch_size: &id034
    - 16
    - 32
    - 64
    - 128
    validation_fraction: &id035
    - 0.1
    - 0.3
    early_stopping_patience: &id036
    - 10
    - 20
    learning_rate: &id037
    - 0.0001
    - 0.01
    hidden_size: &id038
    - 1024
    - 2048
    - 4096
    scheduler_factor: &id039
    - 0.1
    - 0.9
    scheduler_patience: &id040
    - 5
    - 15
- dataset: titanic
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: &id041
      max_epochs: 1000
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 2
      val_size: 0.2
      auto_lr_find: false
    learning_rate: &id042
    - 0.001
    - 0.0001
    early_stopping_patience: &id043
    - 3
    - 5
    virtual_batch_size_ratio: &id044
    - 0.25
    - 0.5
    batch_size: &id045
    - 16
    - 32
    - 64
    weights: &id046
    - 0
    - 1
    mask_type: &id047
    - sparsemax
    - entmax
    n_d: &id048
    - 8
    - 22
    n_steps: &id049
    - 3
    - 10
    gamma: &id050
    - 1.0
    - 2.0
    cat_emb_dim: &id051
    - 1
    - 3
    n_independent: &id052
    - 1
    - 5
    n_shared: &id053
    - 1
    - 5
    lambda_sparse: &id054
    - 0.001
    - 0.01
    momentum: &id055
    - 0.001
    - 0.4
    clip_value: &id056
    - 1
    - 2
    optimizer_fn: &id057
      Adam:
        weight_decay:
        - 0.0001
        - 0.1
    scheduler_fn: &id058
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 7
        - 10
- dataset: titanic
  model: gate
  best_params: {}
  param_grid:
    outer_params: &id059
      hyperopt_evals: 2
      auto_lr_find: false
      max_epochs: 1000
      val_size: 0.2
    learning_rate: &id060
    - 0.001
    - 0.0001
    early_stopping_patience: &id061
    - 10
    - 20
    batch_size: &id062
    - 16
    - 32
    - 64
    - 128
    tree_depth: &id063
    - 4
    - 7
    num_trees: &id064
    - 4
    - 22
    chain_trees: &id065
    - false
    gflu_stages: &id066
    - 2
    - 8
    optimizer_fn: &id067
      Adam:
        weight_decay:
        - 0.0001
        - 0.1
    scheduler_fn: &id068
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 7
        - 10
- dataset: titanic
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: &id069
      max_epochs: 2
      early_stopping_tolerance: 1.0e-06
      hyperopt_evals: 2
      val_size: 0.2
      auto_lr_find: false
    learning_rate: &id070
    - 0.0005
    - 0.001
    - 0.002
    early_stopping_patience: &id071
    - 10
    - 20
    batch_size: &id072
    - 16
    - 32
    - 64
    input_embed_dim: &id073
    - 16
    - 32
    - 64
    embedding_initialization: &id074
    - kaiming_uniform
    - kaiming_normal
    embedding_bias: &id075
    - true
    - false
    share_embedding: &id076
    - true
    - false
    share_embedding_strategy: &id077
    - add
    - fraction
    - add
    shared_embedding_fraction: &id078
    - 0.1
    - 0.25
    - 0.5
    attn_feature_importance: &id079
    - true
    - false
    num_heads: &id080
    - 6
    - 8
    - 10
    num_attn_blocks: &id081
    - 4
    - 6
    - 8
    transformer_head_dim: &id082
    - 64
    - 128
    attn_dropout: &id083
    - 0.05
    - 0.1
    - 0.15
    add_norm_dropout: &id084
    - 0.05
    - 0.1
    - 0.15
    ff_dropout: &id085
    - 0.05
    - 0.1
    - 0.15
    ff_hidden_multiplier: &id086
    - 3
    - 4
    - 5
    transformer_activation: &id087
    - ReLU
    - GEGLU
    - SwiGLU
    embedding_dropout: &id088
    - 0.05
    - 0.1
    - 0.15
    batch_norm_continuous_input: &id089
    - false
    - true
    optimizer_fn: &id090
      Adam:
        weight_decay:
        - 0.0001
        - 0.3
    scheduler_fn: &id091
      ReduceLROnPlateau:
        factor:
        - 0.1
        - 0.9
        patience:
        - 7
        - 10
- dataset: iris
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    validation_fraction: *id003
    max_bin: *id004
    tree_method: *id005
    max_depth: *id006
    learning_rate: *id007
    subsample: *id008
    colsample_bytree: *id009
    min_child_weight: *id010
    alpha: *id011
    gamma: *id012
    lambda: *id013
- dataset: iris
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id014
    hidden_layer_sizes: *id015
    activation: *id016
    solver: *id017
    alpha: *id018
    learning_rate_init: *id019
    beta_1: *id020
    beta_2: *id021
    n_iter_no_change: *id022
    validation_fraction: *id023
    max_iter: *id024
    batch_size: *id025
- dataset: iris
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id026
    learning_rate: *id027
    batch_size: *id028
    validation_fraction: *id029
    early_stopping_patience: *id030
    scheduler_factor: *id031
    scheduler_patience: *id032
- dataset: iris
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id033
    batch_size: *id034
    validation_fraction: *id035
    early_stopping_patience: *id036
    learning_rate: *id037
    hidden_size: *id038
    scheduler_factor: *id039
    scheduler_patience: *id040
- dataset: iris
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id041
    learning_rate: *id042
    early_stopping_patience: *id043
    virtual_batch_size_ratio: *id044
    batch_size: *id045
    weights: *id046
    mask_type: *id047
    n_d: *id048
    n_steps: *id049
    gamma: *id050
    cat_emb_dim: *id051
    n_independent: *id052
    n_shared: *id053
    lambda_sparse: *id054
    momentum: *id055
    clip_value: *id056
    optimizer_fn: *id057
    scheduler_fn: *id058
- dataset: iris
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id059
    learning_rate: *id060
    early_stopping_patience: *id061
    batch_size: *id062
    tree_depth: *id063
    num_trees: *id064
    chain_trees: *id065
    gflu_stages: *id066
    optimizer_fn: *id067
    scheduler_fn: *id068
- dataset: iris
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id069
    learning_rate: *id070
    early_stopping_patience: *id071
    batch_size: *id072
    input_embed_dim: *id073
    embedding_initialization: *id074
    embedding_bias: *id075
    share_embedding: *id076
    share_embedding_strategy: *id077
    shared_embedding_fraction: *id078
    attn_feature_importance: *id079
    num_heads: *id080
    num_attn_blocks: *id081
    transformer_head_dim: *id082
    attn_dropout: *id083
    add_norm_dropout: *id084
    ff_dropout: *id085
    ff_hidden_multiplier: *id086
    transformer_activation: *id087
    embedding_dropout: *id088
    batch_norm_continuous_input: *id089
    optimizer_fn: *id090
    scheduler_fn: *id091
- dataset: housing
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    validation_fraction: *id003
    max_bin: *id004
    tree_method: *id005
    max_depth: *id006
    learning_rate: *id007
    subsample: *id008
    colsample_bytree: *id009
    min_child_weight: *id010
    alpha: *id011
    gamma: *id012
    lambda: *id013
- dataset: housing
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id014
    hidden_layer_sizes: *id015
    activation: *id016
    solver: *id017
    alpha: *id018
    learning_rate_init: *id019
    beta_1: *id020
    beta_2: *id021
    n_iter_no_change: *id022
    validation_fraction: *id023
    max_iter: *id024
    batch_size: *id025
- dataset: housing
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id026
    learning_rate: *id027
    batch_size: *id028
    validation_fraction: *id029
    early_stopping_patience: *id030
    scheduler_factor: *id031
    scheduler_patience: *id032
- dataset: housing
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id033
    batch_size: *id034
    validation_fraction: *id035
    early_stopping_patience: *id036
    learning_rate: *id037
    hidden_size: *id038
    scheduler_factor: *id039
    scheduler_patience: *id040
- dataset: housing
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id041
    learning_rate: *id042
    early_stopping_patience: *id043
    virtual_batch_size_ratio: *id044
    batch_size: *id045
    weights: *id046
    mask_type: *id047
    n_d: *id048
    n_steps: *id049
    gamma: *id050
    cat_emb_dim: *id051
    n_independent: *id052
    n_shared: *id053
    lambda_sparse: *id054
    momentum: *id055
    clip_value: *id056
    optimizer_fn: *id057
    scheduler_fn: *id058
- dataset: housing
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id059
    learning_rate: *id060
    early_stopping_patience: *id061
    batch_size: *id062
    tree_depth: *id063
    num_trees: *id064
    chain_trees: *id065
    gflu_stages: *id066
    optimizer_fn: *id067
    scheduler_fn: *id068
- dataset: housing
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id069
    learning_rate: *id070
    early_stopping_patience: *id071
    batch_size: *id072
    input_embed_dim: *id073
    embedding_initialization: *id074
    embedding_bias: *id075
    share_embedding: *id076
    share_embedding_strategy: *id077
    shared_embedding_fraction: *id078
    attn_feature_importance: *id079
    num_heads: *id080
    num_attn_blocks: *id081
    transformer_head_dim: *id082
    attn_dropout: *id083
    add_norm_dropout: *id084
    ff_dropout: *id085
    ff_hidden_multiplier: *id086
    transformer_activation: *id087
    embedding_dropout: *id088
    batch_norm_continuous_input: *id089
    optimizer_fn: *id090
    scheduler_fn: *id091
- dataset: adult
  model: xgb
  best_params: {}
  param_grid:
    outer_params: *id001
    n_estimators: *id002
    validation_fraction: *id003
    max_bin: *id004
    tree_method: *id005
    max_depth: *id006
    learning_rate: *id007
    subsample: *id008
    colsample_bytree: *id009
    min_child_weight: *id010
    alpha: *id011
    gamma: *id012
    lambda: *id013
- dataset: adult
  model: mlp
  best_params: {}
  param_grid:
    outer_params: *id014
    hidden_layer_sizes: *id015
    activation: *id016
    solver: *id017
    alpha: *id018
    learning_rate_init: *id019
    beta_1: *id020
    beta_2: *id021
    n_iter_no_change: *id022
    validation_fraction: *id023
    max_iter: *id024
    batch_size: *id025
- dataset: adult
  model: resnet
  best_params: {}
  param_grid:
    outer_params: *id026
    learning_rate: *id027
    batch_size: *id028
    validation_fraction: *id029
    early_stopping_patience: *id030
    scheduler_factor: *id031
    scheduler_patience: *id032
- dataset: adult
  model: s1dcnn
  best_params: {}
  param_grid:
    outer_params: *id033
    batch_size: *id034
    validation_fraction: *id035
    early_stopping_patience: *id036
    learning_rate: *id037
    hidden_size: *id038
    scheduler_factor: *id039
    scheduler_patience: *id040
- dataset: adult
  model: tabnet
  best_params: {}
  param_grid:
    outer_params: *id041
    learning_rate: *id042
    early_stopping_patience: *id043
    virtual_batch_size_ratio: *id044
    batch_size: *id045
    weights: *id046
    mask_type: *id047
    n_d: *id048
    n_steps: *id049
    gamma: *id050
    cat_emb_dim: *id051
    n_independent: *id052
    n_shared: *id053
    lambda_sparse: *id054
    momentum: *id055
    clip_value: *id056
    optimizer_fn: *id057
    scheduler_fn: *id058
- dataset: adult
  model: gate
  best_params: {}
  param_grid:
    outer_params: *id059
    learning_rate: *id060
    early_stopping_patience: *id061
    batch_size: *id062
    tree_depth: *id063
    num_trees: *id064
    chain_trees: *id065
    gflu_stages: *id066
    optimizer_fn: *id067
    scheduler_fn: *id068
- dataset: adult
  model: fttransformer
  best_params: {}
  param_grid:
    outer_params: *id069
    learning_rate: *id070
    early_stopping_patience: *id071
    batch_size: *id072
    input_embed_dim: *id073
    embedding_initialization: *id074
    embedding_bias: *id075
    share_embedding: *id076
    share_embedding_strategy: *id077
    shared_embedding_fraction: *id078
    attn_feature_importance: *id079
    num_heads: *id080
    num_attn_blocks: *id081
    transformer_head_dim: *id082
    attn_dropout: *id083
    add_norm_dropout: *id084
    ff_dropout: *id085
    ff_hidden_multiplier: *id086
    transformer_activation: *id087
    embedding_dropout: *id088
    batch_norm_continuous_input: *id089
    optimizer_fn: *id090
    scheduler_fn: *id091
